name: Python Pull Request Workflow
on: [pull_request]

jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest

    steps:
      # Checkout the code using the latest stable version
      - uses: actions/checkout@v2

      # Set up Python using the stable version of setup-python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install poetry and dependencies
      - name: Install poetry
        run: |
          pip install poetry
          poetry install --no-interaction --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: true # Ensures virtualenv creation

      # View poetry help to verify it works correctly
      - name: View poetry --help
        run: poetry --help

      # Check if virtualenv is activated and installed packages
      - name: Check if virtualenv is activated
        run: |
          poetry run python -m venv --help

      - name: List installed packages
        run: |
          poetry run pip list

      # Explicitly install Django if it's missing
      - name: Explicitly add Django
        run: |
          poetry add django
          poetry install --no-interaction

      # Run tests using poetry
      - name: Test
        run: |
          poetry run python manage.py test

      # Run Wemake Python Styleguide
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@0.16.0
        continue-on-error: true
        with:
          reporter: "github-pr-review"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
